### ISSUE TITLE
Requested an insecure image

### ISSUE THREAD

**Issue by Connor-Bowley** [PerkLab/SlicerSandbox#12]
When in the extension manager for Slicer 5.1.0-2022-07-04, if I click on the image for Sandbox, I get errors on the command line, and it does not open the Sandbox page.

Errors are of the sort
```
"https://extensions.slicer.org/view/Sandbox/31077/linux" 0 "Mixed Content: The page at 'https://extensions.slicer.org/view/Sandbox/31077/linux' was loaded over HTTPS, but requested an insecure image 'http://www.slicer.org/slicerWiki/images/c/c2/VolumeClipLogo.png'. This content should also be served over HTTPS."
Mixed Content: The page at 'https://extensions.slicer.org/view/Sandbox/31077/linux' was loaded over HTTPS, but requested an insecure image 'http://www.slicer.org/slicerWiki/images/c/c2/VolumeClipLogo.png'. This content should also be served over HTTPS.
```

**Comment by lassoan** [comment]
Thanks for reporting. The issue is due to a bug in the Extensions Catalog (https://github.com/KitwareMedical/slicer-extensions-webapp/issues/74) that breaks rendering of an extension details page if no screenshots are provided for the extension. I've added some screenshots to the extension description to avoid this issue anyway (https://github.com/PerkLab/SlicerSandbox/commit/c83fdbaeb2d57e61b344204873719240d2220b9e).
